buildscript {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        maven {
            name = "Forge"
            url = uri("https://maven.minecraftforge.net")
        }
    }
    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.10"
        classpath "net.minecraftforge.gradle:ForgeGradle:6.0.22"
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'kotlin'
    apply plugin: 'maven-publish'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(17)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).configureEach {
        kotlinOptions {
            jvmTarget = '17'
            freeCompilerArgs += ['-Xjvm-default=all']
        }
    }

    configurations.all {
        resolutionStrategy {
            eachDependency { DependencyResolveDetails details ->
                if (details.requested.group == 'org.jetbrains.kotlin') {
                    details.useVersion "2.1.10"
                }
            }
        }
    }

    repositories {
        mavenCentral()
        maven {
            name = 'Forge'
            url = uri('https://maven.minecraftforge.net')
        }
        maven {
            name = 'Kotlin for Forge'
            url = 'https://thedarkcolour.github.io/KotlinForForge/'
        }
        maven {
            name = 'Sponge'
            url = uri('https://repo.spongepowered.org/repository/maven-public')
        }
        maven {
            name = 'Fabric'
            url = uri('https://maven.fabricmc.net')
        }
    }
}

project(':common') {
    apply plugin: 'org.jetbrains.kotlin.kapt'
}

project(':forge') {
    dependencies {
        implementation project(':common')
    }
}
