buildscript {
    repositories {
        maven {
            name = "Forge"
            url = uri("https://maven.minecraftforge.net")
        }
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:5.1.50"
    }
}

apply plugin: 'net.minecraftforge.gradle'

tasks.javadoc {
    enabled = false
}

tasks.named('processResources', ProcessResources) {
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
}

minecraft {
    version '1.20.1'
}

tasks.register("sourceWithCommon", Jar) {
    def other = project(":common").tasks.findByName("sourcesJar")
    if (other != null) {
        dependsOn(other)
        from zipTree(other.archiveFile)
    }
    duplicatesStrategy = DuplicatesStrategy.EXCLUDE
    destinationDirectory.set(file("../builds/sources"))
    archiveFileName = "${rootProject.mod_name}-Forge-Source-${rootProject.version}.jar"
}

tasks.named('jar', Jar) {
    destinationDirectory.set(file("../builds/jar"))
    archiveFileName.set("${rootProject.mod_name}-Forge-${rootProject.minecraft_version}-${rootProject.version}.jar")
    dependsOn(tasks.named("sourceWithCommon"))
}

repositories {
    maven {
        name = "Forge"
        url = "https://maven.minecraftforge.net"
    }
    maven {
        name = "Kotlin for Forge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
    maven {
        name = "jsdu-snapshot"
        url = "https://nexus.jsdu.cn/snapshots"
        mavenContent {
            snapshotsOnly()
        }
    }
    maven {
        name = "jsdu"
        url = "https://nexus.jsdu.cn/repository"
    }
    flatDir {
        dirs "../depend"
    }
}

dependencies {
    minecraft "com.mojang:minecraft:1.20.1"
    compileOnly fileTree(dir: "../compile_only_depend", includes: ["*.jar"])
    compileOnly "maven.modrinth:sodium:mc1.20.1-0.5.8-forge"
    implementation "thedarkcolour:kotlinforforge-forge:5.10.0"
    implementation "net.minecraftforge:forge:1.20.1-46.0.14"
    runtimeOnly fileTree(dir: "../depend", includes: ["*.jar"])
}

sourceSets.main.resources {
    srcDir 'src/generated/resources'
}
