package cn.coostack.cooparticlesapi.supports


/**
 * 防止在服务器环境需要提供 RenderType/TextureSheet 名字 然后懒得手打字符串的
 */
enum class TextureSheetsEnum {
    // CooParticlesAPI 提供
    PARTICLE_SHEET_TRANSLUCENT_NO_DEPTH_WRITE,
    ADDITION_BLEND_NOT_HDR,
    ADDITION_BLEND_NOT_HDR_NO_DEPTH_WRITE,
    ADDITION_BLEND_TRANSLUCENT_NOT_HDR,
    ADDITION_BLEND_TRANSLUCENT_NOT_HDR_NO_DEPTH_WRITE,
    ADDITION_BLEND_TRANSLUCENT_NO_DEPTH_WRITE,
    ADDITION_BLEND_TRANSLUCENT,
    ADDITION_BLEND,

    // ParticleRenderType提供
    PARTICLE_SHEET_OPAQUE,
    PARTICLE_SHEET_TRANSLUCENT,
    PARTICLE_SHEET_LIT,
    CUSTOM,
    TERRAIN_SHEET,
    NO_RENDER
}
