buildscript {
    repositories {
        maven {
            name = "Forge"
            url = uri("https://maven.minecraftforge.net")
        }
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:6.0.22"
    }
}

apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.kapt'
apply plugin: 'net.minecraftforge.gradle'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    version "1.20.1"
    mappings channel: 'official', version: '1.20.1'
}

tasks.whenTaskAdded {
    if (name == 'genIntellijRuns' || name == 'genEclipseRuns' || name == 'vscode') {
        enabled = false
    }
}

tasks.javadoc {
    enabled = false
}

dependencies {
    minecraft "net.minecraftforge:forge:1.20.1-47.1.3"
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly "org.ow2.asm:asm:9.7"
    compileOnly "org.ow2.asm:asm-tree:9.7"
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly fileTree(dir: "../compile_only_depend", includes: ["*.jar"])
    implementation fileTree(dir: "../depend", includes: ["*.jar"])
    implementation 'io.github.classgraph:classgraph:4.8.184'
}

tasks.named('jar', Jar) {
    archiveFileName.set("${rootProject.mod_name}-Common-${rootProject.minecraft_version}-${rootProject.version}.jar")
}

sourceSets {
    main {
        java {
            exclude 'cn/coostack/cooparticlesapi/mixin/compat/sodium/**'
        }
        kotlin {
            exclude 'cn/coostack/cooparticlesapi/renderer/terrain/sodium/**'
            exclude 'cn/coostack/cooparticlesapi/CooParticlesAPI.kt'
            exclude 'cn/coostack/cooparticlesapi/CooParticlesAPIClient.kt'
            exclude 'cn/coostack/cooparticlesapi/CooShaderReloadSupport.kt'
            exclude 'cn/coostack/cooparticlesapi/annotations/codec/CodecHelper.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/ReflectUtil.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/ServerCameraUtil.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/PhysicsUtil.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/InterpolatorVec3d.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/InterpolatorVector3f.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/InterpolatorDouble.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/InterpolatorFloat.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/InterpolatorQuaternionf.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/InterpolatorRelativeLocation.kt'
            exclude 'cn/coostack/cooparticlesapi/compat/IrisCompat.kt'
            exclude 'cn/coostack/cooparticlesapi/blocks/**'
            exclude 'cn/coostack/cooparticlesapi/entities/**'
            exclude 'cn/coostack/cooparticlesapi/items/**'
            exclude 'cn/coostack/cooparticlesapi/network/packet/**'
            exclude 'cn/coostack/cooparticlesapi/network/particle/**'
            exclude 'cn/coostack/cooparticlesapi/cparticle/**'
            exclude 'cn/coostack/cooparticlesapi/display/**'
            exclude 'cn/coostack/cooparticlesapi/emitters/**'
            exclude 'cn/coostack/cooparticlesapi/coofx/**'
            exclude 'cn/coostack/cooparticlesapi/renderer/**'
            exclude 'cn/coostack/cooparticlesapi/test/**'
            exclude 'cn/coostack/cooparticlesapi/performance/**'
            exclude 'cn/coostack/cooparticlesapi/supports/**'
            exclude 'cn/coostack/cooparticlesapi/api/**'
            exclude 'cn/coostack/cooparticlesapi/particles/**'
            exclude 'cn/coostack/cooparticlesapi/platform/**'
            exclude 'cn/coostack/cooparticlesapi/data/**'
            exclude 'cn/coostack/cooparticlesapi/listeners/**'
            exclude 'cn/coostack/cooparticlesapi/key/**'
            exclude 'cn/coostack/cooparticlesapi/accessor/**'
            exclude 'cn/coostack/cooparticlesapi/annotations/composition/**'
            exclude 'cn/coostack/cooparticlesapi/annotations/display/**'
            exclude 'cn/coostack/cooparticlesapi/annotations/emitter/**'
            exclude 'cn/coostack/cooparticlesapi/annotations/packet/**'
            exclude 'cn/coostack/cooparticlesapi/annotations/renderer/**'
            exclude 'cn/coostack/cooparticlesapi/network/buffer/**'
            exclude 'cn/coostack/cooparticlesapi/utils/helper/**'
            exclude 'cn/coostack/cooparticlesapi/utils/builder/**'
            exclude 'cn/coostack/cooparticlesapi/barrages/**'
            exclude 'cn/coostack/cooparticlesapi/commands/**'
            exclude 'cn/coostack/cooparticlesapi/event/**'
            exclude 'cn/coostack/cooparticlesapi/extend/**'
            exclude 'cn/coostack/cooparticlesapi/annotations/codec/CodecFieldAccessor.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/Math3DUtil.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/particle/**'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/data/**'
            exclude 'cn/coostack/cooparticlesapi/utils/presets/**'
            exclude 'cn/coostack/cooparticlesapi/utils/RelativeLocation.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/RotationMatrix.kt'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/emitters/**'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/particle/**'
            exclude 'cn/coostack/cooparticlesapi/utils/interpolator/Interpolator.kt'
            exclude 'cn/coostack/cooparticlesapi/animation/**'
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://api.modrinth.com/maven")
        content {
            includeGroup("maven.modrinth")
        }
    }
    maven {
        name = "Forge"
        url = uri("https://maven.minecraftforge.net")
    }
    maven {
        name = "Kotlin for Forge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
}
