buildscript {
    repositories {
        maven {
            name = "Forge"
            url = uri("https://maven.minecraftforge.net")
        }
        gradlePluginPortal()
        mavenCentral()
    }
    dependencies {
        classpath "net.minecraftforge.gradle:ForgeGradle:6.0.22"
    }
}

apply plugin: 'java-library'
apply plugin: 'org.jetbrains.kotlin.kapt'
apply plugin: 'net.minecraftforge.gradle'

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

minecraft {
    version "1.20.1"
    mappings channel: 'official', version: '1.20.1'
}

tasks.named('genIntellijRuns').configure {
    enabled = false
}
tasks.named('genEclipseRuns').configure {
    enabled = false
}
tasks.named('vscode').configure {
    enabled = false
}

tasks.javadoc {
    enabled = false
}

dependencies {
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly "org.ow2.asm:asm:9.7"
    compileOnly "org.ow2.asm:asm-tree:9.7"
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly fileTree(dir: "../compile_only_depend", includes: ["*.jar"])
    implementation fileTree(dir: "../depend", includes: ["*.jar"])
    implementation 'io.github.classgraph:classgraph:4.8.184'
}

tasks.named('jar', Jar) {
    archiveFileName.set("${rootProject.mod_name}-Common-${rootProject.minecraft_version}-${rootProject.version}.jar")
}

sourceSets {
    main {
        java {
            exclude 'cn/coostack/cooparticlesapi/mixin/compat/sodium/**'
        }
        kotlin {
            exclude 'cn/coostack/cooparticlesapi/renderer/terrain/sodium/**'
        }
    }
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://api.modrinth.com/maven")
        content {
            includeGroup("maven.modrinth")
        }
    }
    maven {
        name = "Forge"
        url = uri("https://maven.minecraftforge.net")
    }
    maven {
        name = "Kotlin for Forge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
}
