plugins {
    id 'java-library'
    id 'org.jetbrains.kotlin.jvm'
    id 'org.jetbrains.kotlin.kapt'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}

tasks.javadoc {
    enabled = false
}

dependencies {
    implementation 'net.minecraftforge:forge:1.20.1-47.1.3'
    compileOnly group: 'org.spongepowered', name: 'mixin', version: '0.8.5'
    compileOnly "org.ow2.asm:asm:9.7"
    compileOnly "org.ow2.asm:asm-tree:9.7"
    compileOnly group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly "org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2"
    compileOnly "maven.modrinth:sodium:mc1.20.1-0.5.8-forge"
    annotationProcessor group: 'io.github.llamalad7', name: 'mixinextras-common', version: '0.3.5'
    compileOnly fileTree(dir: "../compile_only_depend", includes: ["*.jar"])
    implementation fileTree(dir: "../depend", includes: ["*.jar"])
    implementation 'io.github.classgraph:classgraph:4.8.184'
}

tasks.named('jar', Jar) {
    archiveFileName.set("${rootProject.mod_name}-Common-${rootProject.minecraft_version}-${rootProject.version}.jar")
}

repositories {
    mavenCentral()
    maven {
        url = uri("https://api.modrinth.com/maven")
        content {
            includeGroup("maven.modrinth")
        }
    }
    maven {
        name = "Forge"
        url = uri("https://maven.minecraftforge.net")
    }
    maven {
        name = "Kotlin for Forge"
        url = "https://thedarkcolour.github.io/KotlinForForge/"
    }
}
